"""MsPacman benchmark-derived save-memory ratios for heap sizing."""

import re
from typing import Optional

import numpy as np

# Generated by scripts/fit_heap_heuristic.py — MsPacman Save Mem benchmark
# Extrapolation: poly eval, clamp to family benchmark min/max ratio;
# outside measured level range -> max(fitted, family_max_ratio).
_SAVE_RATIO_BASELINE = 1.0
_SAVE_RATIO_NONE = 1.001
_SAVE_RATIO_RLE = 0.753
_DEFAULT_ZSTD_LEVEL = -3

_ZSTD_POLY = (6.57576906583e-07, 6.67876050886e-05, -0.00283232258306, 0.0656261474215)
_ZSTD_BOUNDS = (-100, 22, 0.044, 0.36)
_GZIP_POLY = (-0.01, 0.106)
_GZIP_BOUNDS = (1, 3, 0.076, 0.096)
_IGZIP_POLY = (-0.000333333333333, -0.0136666666667, 0.12)
_IGZIP_BOUNDS = (0, 3, 0.076, 0.12)
_LZ4_FRAME_POLY = (-0.000102949134199, 0.00270048701299, -0.0227614989177, 0.129163961039)
_LZ4_FRAME_BOUNDS = (1, 12, 0.067, 0.109)
_LZ4_BLOCK_POLY = (-4.65367965368e-06, 0.000194805194805, -0.00277456709957, 0.0795844155844)
_LZ4_BLOCK_BOUNDS = (1, 16, 0.066, 0.077)

_BENCHMARK_FAMILIES = frozenset({"baseline", "none", "rle", "zstd", "gzip", "igzip", "lz4-frame", "lz4-block"})

_METHOD_SUFFIX_RE = re.compile(r"^((?:[A-Za-z]+)|(?:[\w\-]+/))(\-?[0-9]+)$")


def parse_compression_method(method: str) -> tuple[str, Optional[int]]:
    """Split shorthand into ``(family, level)`` matching buffer compression parsing."""
    if method[-1].isdigit() or (len(method) > 1 and method[-1] == "-" and method[-2].isdigit()):
        match = _METHOD_SUFFIX_RE.match(method)
        if not match:
            raise ValueError(f"Invalid compression shorthand: {method}")
        family = match.group(1).removesuffix("/")
        level = int(match.group(2))
        return family, level
    return method, None


def validate_compresslevel(family: str, level: int) -> None:
    """Raise if ``level`` is outside the documented codec range."""
    if family == "gzip" and not 0 <= level <= 9:
        raise ValueError(f"gzip level must be 0-9, got {level}")
    if family == "igzip" and not 0 <= level <= 3:
        raise ValueError(f"igzip level must be 0-3, got {level}")
    if family == "zstd":
        if level == 0 or (level > 22) or (level < -100) or (-1 < level < 1):
            raise ValueError(f"zstd level must be 1-22 or -100--1, got {level}")
    if family == "lz4-frame" and level > 16:
        raise ValueError(f"lz4-frame level must be <= 16 (negative allowed), got {level}")
    if family == "lz4-block":
        if level > 12 or level < -100:
            raise ValueError(f"lz4-block level must be -100..12 (0 default, 1-12 high), got {level}")


def poly_save_ratio(level: int, coeffs: tuple[float, ...], bounds: tuple[int, int, float, float]) -> float:
    """Evaluate fitted polynomial with benchmark clamp and outside-hull safety."""
    min_level, max_level, min_ratio, max_ratio = bounds
    fitted = float(np.polyval(coeffs, level))
    fitted = max(min_ratio, min(max_ratio, fitted))
    if level < min_level or level > max_level:
        fitted = max(fitted, max_ratio)
    return fitted


def resolve_compresslevel(family: str, parsed_level: Optional[int], compresslevel: Optional[int]) -> Optional[int]:
    """Choose effective level: explicit ``compresslevel`` overrides the method suffix."""
    if compresslevel is not None:
        return compresslevel
    if family == "zstd" and parsed_level is None:
        return _DEFAULT_ZSTD_LEVEL
    return parsed_level


def estimate_save_ratio(
    compression_method: str,
    compresslevel: Optional[int] = None,
) -> float:
    """Return Save Mem ratio vs baseline for ``compression_method`` (MsPacman benchmark)."""
    family, parsed_level = parse_compression_method(compression_method)
    level = resolve_compresslevel(family, parsed_level, compresslevel)

    if family in ("baseline",):
        return _SAVE_RATIO_BASELINE
    if family == "none":
        return _SAVE_RATIO_NONE
    if family == "rle":
        return _SAVE_RATIO_RLE

    if family == "zstd":
        if level is None:
            level = _DEFAULT_ZSTD_LEVEL
        validate_compresslevel(family, level)
        return poly_save_ratio(level, _ZSTD_POLY, _ZSTD_BOUNDS)
    if family == "gzip":
        if level is None:
            raise ValueError("gzip requires a compression level (0-9)")
        validate_compresslevel(family, level)
        return poly_save_ratio(level, _GZIP_POLY, _GZIP_BOUNDS)
    if family == "igzip":
        if level is None:
            raise ValueError("igzip requires a compression level (0-3)")
        validate_compresslevel(family, level)
        return poly_save_ratio(level, _IGZIP_POLY, _IGZIP_BOUNDS)
    if family == "lz4-frame":
        if level is None:
            raise ValueError("lz4-frame requires a compression level")
        validate_compresslevel(family, level)
        return poly_save_ratio(level, _LZ4_FRAME_POLY, _LZ4_FRAME_BOUNDS)
    if family == "lz4-block":
        if level is None:
            raise ValueError("lz4-block requires a compression level")
        validate_compresslevel(family, level)
        return poly_save_ratio(level, _LZ4_BLOCK_POLY, _LZ4_BLOCK_BOUNDS)

    return legacy_save_ratio(family, level)


def legacy_save_ratio(family: str, level: Optional[int]) -> float:
    """Analytic worst-case ratio for unknown families (pre-benchmark heuristic)."""
    del family, level
    return 2.0


def is_benchmark_family(family: str) -> bool:
    """Return whether ``family`` has a benchmark-derived save ratio model."""
    return family in _BENCHMARK_FAMILIES
